name: Publish container image
on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: go mod download
    - name: Install redis
      run: sudo apt-get install -y -qq redis-server
    - name: Run tests
      run: go test -v -race ./...
  push:
    needs: test
    name: Build and push container image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: gen-tag
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          echo IMAGE_TAG | tee ci-version.txt
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: |
            ghcr.io/doist/bitmapist-server:${{ steps.gen-tag.outputs.tag }}
            ghcr.io/doist/bitmapist-server:latest
          outputs: type=image,oci-mediatypes=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
