name: Create release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.0.0'
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: go mod download
    - name: Install redis
      run: sudo apt-get install -y -qq redis-server
    - name: Run tests
      run: go test -v -race ./...
    - name: Build and archive
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build \
          -trimpath -ldflags="-s -w -X=main.explicitVersion=${GITHUB_REF##*/}" -o bitmapist-server
        tar czvf bitmapist-server-linux-amd64.tar.gz bitmapist-server

        GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build \
          -trimpath -ldflags="-s -w -X=main.explicitVersion=${GITHUB_REF##*/}" -o bitmapist-server
        tar czvf bitmapist-server-linux-arm64.tar.gz bitmapist-server
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref }} bitmapist-server-*.tar.gz
